### ISSUE TITLE
Get location took forever, Address: Loading ...

### ISSUE THREAD

**Issue by Moanrisy** [AndraBrata/WalkMyAndroid#1]
**Step to produce**
After allow location permissoin
Click button start tracking location
Address: Loading ...  (this took forever) when gps off

**Solution**
After Turn on location / turn on GPS
Application get location properly

**Fix**
Need to check GPS on / off 
or Give warning if GPS off

**Comment by AndraBrata** [comment]
Good..
This app is only starter code..
Improve it to learn more usages..
